name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        envoy-tag:
          - "v1.20.6"
          - "v1.21.4"
          - "v1.22.2"
          - "v1.23.0"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: dcard/envoy
          tags: |
            type=semver,pattern=v{{version}},value=${{ matrix.envoy-tag }}
            type=semver,pattern=v{{major}}.{{minor}},value=${{ matrix.envoy-tag }}
          flavor: |
            latest=${{ startsWith(matrix.envoy-tag, 'v1.23.') }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: ENVOY_TAG=${{ matrix.envoy-tag }}
